production:
  solr:
    hostname: localhost
    port: 8983 #tomcat defaults to port 8080
    # path: '/solr'
    log_level: WARNING
    pid_dir: '/var/run'
    solr_home: solr

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    # pid_dir: defaults to 'app/solr/pids/development'
    # bind_address: defaults to '0.0.0.0' which binds to every interface
  disabled: false # note that this is not indented within `solr`

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
