set :user, 'vagrant'
set :domain, '192.168.33.13'
set :deploy_to, '/var/www/railsapp'
set :repository, 'https://github.com/phanviet/rails-app'
set :branch, 'master'
set :rails_env, 'production'
set :group, 'vagrant'

set :db_host    , '<%= ENV["DB_HOST"] %>'
set :db_database, '<%= ENV["DB_DATABASE"] %>'
set :db_username, '<%= ENV["DB_USERNAME"] %>'
set :db_password, '<%= ENV["DB_PASSWORD"] %>'

set :solr_host    , '<%= ENV["SOLR_HOST"] %>'
set :solr_port    , '<%= ENV["SOLR_PORT"] %>'
set :solr_path    , '<%= ENV["SOLR_PATH"] %>'
set :solr_user    , '<%= ENV["SOLR_USER"] %>'
set :solr_password, '<%= ENV["SOLR_PASSWORD"] %>'
set :solr_role    , '<%= ENV["SOLR_ROLE"] %>'
